# Please note, changes to this file will not invalidate previously made wands.
# Wands are validated through a tag in their Persistent Data Container.
silence-wand:
  custom-name: "<yellow>Shush Stick</yellow>"
  item-type: STICK
  item-model: ""
  enchantment-glint: true
  command-cooldown-seconds: 600
mobs:
  - CHICKEN
  - COW
  - PIG
  - SHEEP
  - ZOMBIE
  - SKELETON
  - WITCH
  - SPIDER
  - VILLAGER
max-radius: 10.0