name: ShutTheCluckUp
version: '0.0.0'
main: simplexity.shutthecluckup.ShutTheCluckUp
api-version: '1.21.4'
commands:
  silence-wand:
    description: gives wand
    permission: silence.wand
  silence-mobs:
    description: allows using a command to silence mobs in a radius
    permission: silence.command
  silence-reload:
    description: allows reloading the plugin configuration
    permission: silence.reload
permissions:
  silence.reload:
    default: op
    description: Allows reloading of the plugin configuration
  silence.wand:
    default: op
    description: Allows command for getting a wand
  silence.other.wand:
    default: op
    description: Allows giving a wand to another player
  silence.mobs.basic:
    default: op
    description: Allows silencing configured mobs
  silence.command:
    default: op
    description: allows usage of a command to silence mobs in a radius
  silence.bypass.mob-type:
    default: op
    description: Bypass all configured mob types, silence any mob
  silence.bypass.cooldown:
    default: op
    description: Bypass the wand command cooldown
  silence.bypass.radius:
    default: op
    description: Bypass the configured max radius
