name: ShutTheCluckUp
version: '0.0.0'
main: simplexity.shutthecluckup.ShutTheCluckUp
api-version: '1.21.4'
commands:
  silence-wand:
    description: gives wand
    permission: silence.wand
permissions:
  silence.wand:
    default: op
    description: Allows command for getting a wand
  silence.other.wand:
    default: op
    description: Allows giving a wand to another player
  silence.mobs.basic:
    default: op
    description: Allows silencing configured mobs
  silence.bypass.mob-type:
    default: op
    description: Bypass all configured mob types, silence any mob
  silence.bypass.cooldown:
    default: op
    description: Bypass the wand command cooldown
  silence.bypass.radius:
    default: op
    description: Bypass the configured max radius
